# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='extract',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_del',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='request',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='case',
            name='validate',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='case',
            name='variables',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='case',
            table='api_case',
        ),
    ]
