# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0002_auto_20180318_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.Project'),
        ),
    ]
