# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0003_case_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='test_manager.BaseModel')),
                ('suite_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('variables', models.CharField(blank=True, max_length=1024, null=True)),
                ('parameters', models.CharField(blank=True, max_length=1024, null=True)),
                ('request', models.CharField(blank=True, max_length=1024, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.Project')),
            ],
            options={
                'db_table': 'test_suite',
            },
            bases=('test_manager.basemodel',),
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='project_id',
        ),
        migrations.AddField(
            model_name='case',
            name='parameters',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='suite_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.Suite'),
        ),
    ]
