# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0004_auto_20180319_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='request',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterModelTable(
            name='case',
            table='test_case',
        ),
    ]
