# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0005_auto_20180323_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='parameters',
        ),
    ]
