# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0006_remove_suite_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='parameters',
        ),
    ]
