# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('variables', models.CharField(blank=True, max_length=500, null=True)),
                ('request', models.TextField(default=None)),
                ('extract', models.CharField(blank=True, max_length=500, null=True)),
                ('validate', models.CharField(default=None, max_length=500)),
                ('is_del', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'test_case',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pro_project',
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('suite_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('variables', models.CharField(blank=True, max_length=1024, null=True)),
                ('request', models.TextField(blank=True, max_length=1024, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.Project')),
            ],
            options={
                'db_table': 'test_suite',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='suite_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_manager.Suite'),
        ),
    ]
