# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1024)),
                ('department', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
    ]
